export const carCatalog = [
  {
    id: "aurora-s7",
    name: "Aurora S7",
    brand: "Lucent",
    model: "S7",
    location: "Lagos",
    type: "Electric",
    pricePerDay: 85000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    summary:
      "Low-noise luxury EV for city transfers, airport runs, and executive weekends.",
  },
  {
    id: "summit-x5",
    name: "Summit X5",
    brand: "Ridge",
    model: "X5",
    location: "Abuja",
    type: "SUV",
    pricePerDay: 68000,
    seats: 7,
    transmission: "Automatic",
    fuel: "Hybrid",
    summary:
      "Spacious family SUV with elevated ride comfort and luggage-friendly storage.",
  },
  {
    id: "velar-r",
    name: "Velar R",
    brand: "Aster",
    model: "Velar R",
    location: "Port Harcourt",
    type: "Luxury",
    pricePerDay: 110000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    summary:
      "High-touch premium ride for weddings, executive travel, and polished arrivals.",
  },
  {
    id: "metro-q2",
    name: "Metro Q2",
    brand: "Nova",
    model: "Q2",
    location: "Lagos",
    type: "Compact",
    pricePerDay: 28000,
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    summary:
      "Smart compact option for short city loops, solo travel, and easy parking.",
  },
  {
    id: "atlas-gt",
    name: "Atlas GT",
    brand: "Northstar",
    model: "GT",
    location: "Ibadan",
    type: "Sedan",
    pricePerDay: 46000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    summary:
      "Business-friendly sedan with quiet comfort and lower daily running costs.",
  },
  {
    id: "cargo-v9",
    name: "Cargo V9",
    brand: "Mova",
    model: "V9",
    location: "Abuja",
    type: "Van",
    pricePerDay: 62000,
    seats: 9,
    transmission: "Automatic",
    fuel: "Diesel",
    summary:
      "People-mover van for airport runs, group transport, and event schedules.",
  },
  {
    id: "solstice-e4",
    name: "Solstice E4",
    brand: "Nova",
    model: "E4",
    location: "Enugu",
    type: "Electric",
    pricePerDay: 78000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    summary:
      "Comfort-focused electric crossover built for quieter long city days.",
  },
  {
    id: "trail-h1",
    name: "Trail H1",
    brand: "Granite",
    model: "H1",
    location: "Kano",
    type: "SUV",
    pricePerDay: 54000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Diesel",
    summary:
      "Practical SUV for highway drives, regional trips, and mixed road surfaces.",
  },
  {
    id: "toyota-fortuner-gx",
    name: "Fortuner GX",
    brand: "Toyota",
    model: "Fortuner GX",
    location: "Lagos",
    type: "SUV",
    pricePerDay: 66000,
    seats: 7,
    transmission: "Automatic",
    fuel: "Diesel",
    summary:
      "Reliable Toyota SUV for family travel, intercity drives, and secure road presence.",
  },
  {
    id: "peugeot-3008-gt",
    name: "3008 GT",
    brand: "Peugeot",
    model: "3008 GT",
    location: "Abuja",
    type: "SUV",
    pricePerDay: 58000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    summary:
      "Hybrid Peugeot crossover suited for business errands and premium city comfort.",
  },
  {
    id: "honda-accord-touring",
    name: "Accord Touring",
    brand: "Honda",
    model: "Accord Touring",
    location: "Port Harcourt",
    type: "Sedan",
    pricePerDay: 50000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    summary:
      "Clean executive sedan for weekday business travel and confident highway cruising.",
  },
  {
    id: "kia-sportage-lx",
    name: "Sportage LX",
    brand: "Kia",
    model: "Sportage LX",
    location: "Benin City",
    type: "SUV",
    pricePerDay: 56000,
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    summary:
      "Balanced Kia crossover for family errands, weekend travel, and everyday comfort.",
  },
];

const carSummaryById = new Map(carCatalog.map((car) => [car.id, car]));

export function getCarSummary(carId) {
  return carSummaryById.get(carId) ?? null;
}
