import type { Car, CarGalleryImage } from "@/lib/types";

const pexelsPhoto = (id: string) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1600`;

const galleryImage = (
  src: string,
  label: string,
  alt: string,
): CarGalleryImage => ({
  src,
  label,
  alt,
});

const pexels = {
  luxuryFront: pexelsPhoto("35252958"),
  sportsProfile: pexelsPhoto("3972755"),
  showroomBlack: pexelsPhoto("4141954"),
  graphiteSedan: pexelsPhoto("12681081"),
  luxuryWagon: pexelsPhoto("11770453"),
  suvSide: pexelsPhoto("14719372"),
  suvFront: pexelsPhoto("7154531"),
  blackJeep: pexelsPhoto("3370332"),
  luxuryVan: pexelsPhoto("18029633"),
  vanInterior: pexelsPhoto("18029638"),
  urbanSedan: pexelsPhoto("20582976"),
  interiorLeather: pexelsPhoto("9792965"),
  interiorBMW: pexelsPhoto("8192659"),
  interiorDisplay: pexelsPhoto("3778768"),
  interiorConsole: pexelsPhoto("12681060"),
  toyotaFortunerFront: pexelsPhoto("105296"),
  toyotaFortunerForest: pexelsPhoto("11143602"),
  toyotaFortunerRear: pexelsPhoto("18240248"),
  toyotaFortunerTrail: pexelsPhoto("11143608"),
  peugeot3008Parked: pexelsPhoto("14141339"),
  peugeot3008Night: pexelsPhoto("26587382"),
  peugeot3008Rain: pexelsPhoto("10561897"),
  hondaAccordFront: pexelsPhoto("16387777"),
  hondaAccordStreet: pexelsPhoto("16350076"),
  hondaAccordRear: pexelsPhoto("16387775"),
  hondaAccordCloseup: pexelsPhoto("16387776"),
  hondaAccordSide: pexelsPhoto("18016148"),
  kiaSportageFront: pexelsPhoto("27286179"),
  kiaSportageRear: pexelsPhoto("27284257"),
  kiaSportageAdventure: pexelsPhoto("5633405"),
  kiaSportageOffroad: pexelsPhoto("20400581"),
} as const;

export const cars: Car[] = [
  {
    id: "aurora-s7",
    name: "Aurora S7",
    brand: "Lucent",
    model: "S7",
    year: 2025,
    type: "Electric",
    location: "Lagos",
    pricePerDay: 85000,
    rating: 4.9,
    trips: 124,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    range: "520 km",
    featured: true,
    summary: "Low-noise luxury EV for city transfers, airport runs, and executive weekends.",
    description:
      "Aurora S7 pairs calm electric performance with a cabin tuned for long conversations, smooth navigation, and all-day comfort.",
    features: [
      "Panoramic glass roof",
      "Adaptive cruise control",
      "Fast charging support",
      "Ventilated front seats",
      "Wireless Apple CarPlay",
    ],
    heroImage: pexels.luxuryFront,
    gallery: [
      galleryImage(
        pexels.luxuryFront,
        "Arrival front view",
        "Front view of a sleek luxury car parked in an urban setting",
      ),
      galleryImage(
        pexels.sportsProfile,
        "Side profile",
        "Low side profile of a luxury coupe in a moody outdoor setting",
      ),
      galleryImage(
        pexels.interiorDisplay,
        "Digital cockpit",
        "Luxury car cockpit with steering wheel, console, and digital screens",
      ),
      galleryImage(
        pexels.interiorBMW,
        "Driver cabin",
        "Premium car interior showing steering wheel, dashboard, and front cabin details",
      ),
    ],
    imageAlt: "Front view of a sleek luxury car parked in an urban setting",
    palette: {
      from: "#101114",
      to: "#404247",
      accent: "#d8b870",
    },
  },
  {
    id: "summit-x5",
    name: "Summit X5",
    brand: "Ridge",
    model: "X5",
    year: 2024,
    type: "SUV",
    location: "Abuja",
    pricePerDay: 68000,
    rating: 4.8,
    trips: 98,
    seats: 7,
    transmission: "Automatic",
    fuel: "Hybrid",
    range: "780 km",
    featured: true,
    summary: "Spacious family SUV with elevated ride comfort and luggage-friendly storage.",
    description:
      "Summit X5 is designed for long intercity drives, road trips, and family travel with enough room for everyone and everything.",
    features: [
      "Three-row seating",
      "360 camera system",
      "Split climate zones",
      "Hands-free tailgate",
      "Terrain assist",
    ],
    heroImage: pexels.suvSide,
    gallery: [
      galleryImage(
        pexels.suvSide,
        "Side profile",
        "Black luxury SUV photographed in profile on a rooftop parking deck",
      ),
      galleryImage(
        pexels.suvFront,
        "Front quarter view",
        "Front view of a dark SUV parked outdoors in soft daylight",
      ),
      galleryImage(
        pexels.blackJeep,
        "Street-ready stance",
        "Black SUV parked curbside in an upscale urban district",
      ),
      galleryImage(
        pexels.interiorLeather,
        "Family cabin",
        "Leather-trimmed car interior with modern dashboard and cabin controls",
      ),
    ],
    imageAlt: "Black luxury SUV photographed in profile on a rooftop parking deck",
    palette: {
      from: "#111318",
      to: "#494d53",
      accent: "#c3a35d",
    },
  },
  {
    id: "velar-r",
    name: "Velar R",
    brand: "Aster",
    model: "Velar R",
    year: 2024,
    type: "Luxury",
    location: "Port Harcourt",
    pricePerDay: 110000,
    rating: 4.95,
    trips: 56,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    range: "640 km",
    featured: true,
    summary: "High-touch premium ride for weddings, executive travel, and polished arrivals.",
    description:
      "Velar R leans into quiet confidence with refined suspension, sculpted interiors, and premium detailing in every touchpoint.",
    features: [
      "Massage seats",
      "Rear privacy glass",
      "Premium surround audio",
      "Driver assistance suite",
      "Ambient lighting",
    ],
    heroImage: pexels.showroomBlack,
    gallery: [
      galleryImage(
        pexels.showroomBlack,
        "Showroom exterior",
        "Black luxury car photographed inside a polished showroom",
      ),
      galleryImage(
        pexels.luxuryFront,
        "Arrival angle",
        "Luxury sedan front view parked outside a modern building",
      ),
      galleryImage(
        pexels.interiorBMW,
        "Executive cockpit",
        "Upscale BMW-style interior featuring premium dashboard and steering wheel",
      ),
      galleryImage(
        pexels.interiorConsole,
        "Console detail",
        "Luxury center console and gear selector inside a premium car cabin",
      ),
    ],
    imageAlt: "Black luxury car photographed inside a polished showroom",
    palette: {
      from: "#111216",
      to: "#3a3d42",
      accent: "#dcc07f",
    },
  },
  {
    id: "metro-q2",
    name: "Metro Q2",
    brand: "Nova",
    model: "Q2",
    year: 2023,
    type: "Compact",
    location: "Lagos",
    pricePerDay: 28000,
    rating: 4.7,
    trips: 211,
    seats: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    range: "560 km",
    featured: false,
    summary: "Smart compact option for short city loops, solo travel, and easy parking.",
    description:
      "Metro Q2 keeps things efficient without feeling bare, giving you a responsive ride and a polished city-first cabin.",
    features: [
      "Reverse camera",
      "Compact parking assist",
      "USB-C charging",
      "Fold-flat rear seats",
      "Keyless start",
    ],
    heroImage: pexels.graphiteSedan,
    gallery: [
      galleryImage(
        pexels.graphiteSedan,
        "City profile",
        "Graphite sedan parked roadside with gold rims and a low luxury stance",
      ),
      galleryImage(
        pexels.urbanSedan,
        "Front curb view",
        "Black luxury sedan parked in front of an urban brick wall",
      ),
      galleryImage(
        pexels.interiorLeather,
        "Cabin seating",
        "Modern leather-trimmed car interior with refined seating and console lines",
      ),
      galleryImage(
        pexels.interiorDisplay,
        "Driver display",
        "Minimal luxury dashboard with digital display and steering wheel view",
      ),
    ],
    imageAlt: "Graphite sedan parked roadside with gold rims and a low luxury stance",
    palette: {
      from: "#15161a",
      to: "#43464b",
      accent: "#d4b26b",
    },
  },
  {
    id: "atlas-gt",
    name: "Atlas GT",
    brand: "Helix",
    model: "GT",
    year: 2025,
    type: "Sedan",
    location: "Ibadan",
    pricePerDay: 46000,
    rating: 4.8,
    trips: 88,
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    range: "860 km",
    featured: false,
    summary: "Balanced sedan for business schedules, commute comfort, and strong fuel economy.",
    description:
      "Atlas GT blends hybrid efficiency with a stable, composed ride that feels equally right for meetings and weekend plans.",
    features: [
      "Lane keep assist",
      "Noise-insulated cabin",
      "Dual-zone climate control",
      "Heated seats",
      "Smartphone key",
    ],
    heroImage: pexels.luxuryWagon,
    gallery: [
      galleryImage(
        pexels.luxuryWagon,
        "Roadside profile",
        "Black performance wagon parked on a premium rooftop lot",
      ),
      galleryImage(
        pexels.urbanSedan,
        "Executive front angle",
        "Black luxury sedan framed by an urban industrial backdrop",
      ),
      galleryImage(
        pexels.interiorBMW,
        "Driver cockpit",
        "Premium steering wheel and dashboard inside a luxury executive sedan",
      ),
      galleryImage(
        pexels.interiorConsole,
        "Center console",
        "Gear selector and control console detail in a premium vehicle interior",
      ),
    ],
    imageAlt: "Black performance wagon parked on a premium rooftop lot",
    palette: {
      from: "#101216",
      to: "#41454b",
      accent: "#d3b16c",
    },
  },
  {
    id: "cargo-v9",
    name: "Cargo V9",
    brand: "Rove",
    model: "V9",
    year: 2024,
    type: "Van",
    location: "Abuja",
    pricePerDay: 62000,
    rating: 4.75,
    trips: 67,
    seats: 9,
    transmission: "Manual",
    fuel: "Diesel",
    range: "920 km",
    featured: false,
    summary: "People-mover built for group pickups, event shuttles, and airport logistics.",
    description:
      "Cargo V9 is configured for coordinated travel with wide access, serious storage space, and reliable diesel efficiency.",
    features: [
      "9-seat layout",
      "Wide sliding doors",
      "Rear cargo shelf",
      "Roof rack support",
      "Dual battery system",
    ],
    heroImage: pexels.luxuryVan,
    gallery: [
      galleryImage(
        pexels.luxuryVan,
        "Arrival exterior",
        "Black premium shuttle van parked outdoors",
      ),
      galleryImage(
        pexels.vanInterior,
        "Passenger cabin",
        "Rear passenger seating inside a spacious premium shuttle van",
      ),
      galleryImage(
        pexels.interiorLeather,
        "Driver cabin",
        "Practical leather-trimmed dashboard and front seating area in a vehicle cabin",
      ),
      galleryImage(
        pexels.interiorDisplay,
        "Control console",
        "Center display and steering controls inside a modern transport vehicle",
      ),
    ],
    imageAlt: "Black premium shuttle van parked outdoors",
    palette: {
      from: "#111317",
      to: "#42464c",
      accent: "#d0af69",
    },
  },
  {
    id: "solstice-e4",
    name: "Solstice E4",
    brand: "Prism",
    model: "E4",
    year: 2025,
    type: "Electric",
    location: "Enugu",
    pricePerDay: 78000,
    rating: 4.85,
    trips: 48,
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    range: "470 km",
    featured: false,
    summary: "Stylish EV crossover with quick charging and a calm lounge-like cabin.",
    description:
      "Solstice E4 feels modern without trying too hard, combining practical crossover space with an all-electric ride.",
    features: [
      "Quick-charge battery",
      "One-pedal driving mode",
      "Memory driver profile",
      "Frameless display",
      "Surround parking sensors",
    ],
    heroImage: pexels.sportsProfile,
    gallery: [
      galleryImage(
        pexels.sportsProfile,
        "Performance side view",
        "Low sports coupe parked in profile with a moody luxury finish",
      ),
      galleryImage(
        pexels.luxuryFront,
        "Front stance",
        "Sleek electric-style sedan shown from the front in a city setting",
      ),
      galleryImage(
        pexels.interiorDisplay,
        "Minimal cockpit",
        "Modern electric car dashboard with a clean digital instrument layout",
      ),
      galleryImage(
        pexels.interiorBMW,
        "Cabin detail",
        "Premium front cabin with leather trim and steering wheel controls",
      ),
    ],
    imageAlt: "Low sports coupe parked in profile with a moody luxury finish",
    palette: {
      from: "#101216",
      to: "#45484d",
      accent: "#d7bb76",
    },
  },
  {
    id: "trail-h1",
    name: "Trail H1",
    brand: "Northline",
    model: "H1",
    year: 2023,
    type: "SUV",
    location: "Kano",
    pricePerDay: 54000,
    rating: 4.72,
    trips: 102,
    seats: 5,
    transmission: "Automatic",
    fuel: "Diesel",
    range: "830 km",
    featured: false,
    summary: "Tougher SUV for rougher routes, longer drives, and mixed city-to-outskirts travel.",
    description:
      "Trail H1 is built for confidence on unpredictable roads, with a planted stance and practical all-purpose interior.",
    features: [
      "Hill descent control",
      "All-weather tires",
      "Tow-ready kit",
      "Large cargo bay",
      "Offline navigation mode",
    ],
    heroImage: pexels.blackJeep,
    gallery: [
      galleryImage(
        pexels.blackJeep,
        "Urban exterior",
        "Black SUV parked curbside in an upscale urban district",
      ),
      galleryImage(
        pexels.suvFront,
        "Front stance",
        "Front-quarter SUV view with a planted road-trip-ready stance",
      ),
      galleryImage(
        pexels.suvSide,
        "Side angle",
        "Side profile of a dark SUV with elevated ride height",
      ),
      galleryImage(
        pexels.interiorLeather,
        "Cabin interior",
        "Comfortable leather-trimmed SUV-style interior with a practical dashboard layout",
      ),
    ],
    imageAlt: "Black SUV parked curbside in an upscale urban district",
    palette: {
      from: "#101114",
      to: "#3f4348",
      accent: "#d1ae68",
    },
  },
  {
    id: "toyota-fortuner-gx",
    name: "Fortuner GX",
    brand: "Toyota",
    model: "Fortuner",
    year: 2024,
    type: "SUV",
    location: "Lagos",
    pricePerDay: 66000,
    rating: 4.81,
    trips: 141,
    seats: 7,
    transmission: "Automatic",
    fuel: "Diesel",
    range: "870 km",
    featured: false,
    summary: "Trusted Toyota SUV for airport pickups, family travel, and steady intercity movement.",
    description:
      "Fortuner GX brings Toyota reliability into the premium fleet with a roomy cabin, stable ride height, and dependable long-range comfort.",
    features: [
      "Third-row seating",
      "Hill assist control",
      "Rear camera",
      "Dual-zone climate",
      "Large luggage capacity",
    ],
    heroImage: pexels.toyotaFortunerFront,
    gallery: [
      galleryImage(
        pexels.toyotaFortunerFront,
        "Front road view",
        "White Toyota Fortuner photographed from the front on a bright city road",
      ),
      galleryImage(
        pexels.toyotaFortunerForest,
        "Forest front view",
        "Black Toyota Fortuner parked near the woods under soft daylight",
      ),
      galleryImage(
        pexels.toyotaFortunerRear,
        "Rear angle",
        "Rear view of a white Toyota Fortuner standing in a parking lot",
      ),
      galleryImage(
        pexels.toyotaFortunerTrail,
        "Trail drive",
        "Toyota Fortuner SUV driving through a lush forest trail",
      ),
    ],
    imageAlt: "White Toyota Fortuner photographed from the front on a bright city road",
    palette: {
      from: "#101317",
      to: "#46525b",
      accent: "#7fd0ff",
    },
  },
  {
    id: "peugeot-3008-gt",
    name: "3008 GT",
    brand: "Peugeot",
    model: "3008",
    year: 2024,
    type: "SUV",
    location: "Abuja",
    pricePerDay: 58000,
    rating: 4.76,
    trips: 89,
    seats: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    range: "690 km",
    featured: false,
    summary: "Sharp Peugeot crossover for polished city meetings and flexible weekend drives.",
    description:
      "3008 GT gives the fleet a more design-forward crossover option, pairing a composed ride with a cabin that feels refined without being flashy.",
    features: [
      "Digital instrument cluster",
      "Adaptive headlights",
      "Panoramic roof",
      "Wireless charging",
      "Driver assistance pack",
    ],
    heroImage: pexels.peugeot3008Parked,
    gallery: [
      galleryImage(
        pexels.peugeot3008Parked,
        "Parked front view",
        "Silver Peugeot 3008 parked in a cobblestone alley",
      ),
      galleryImage(
        pexels.peugeot3008Night,
        "Night city drive",
        "Peugeot 3008 driving on a dimly lit city street at night",
      ),
      galleryImage(
        pexels.peugeot3008Rain,
        "Rainy road angle",
        "Peugeot 3008 captured on a rainy road in New South Wales",
      ),
    ],
    imageAlt: "Silver Peugeot 3008 parked in a cobblestone alley",
    palette: {
      from: "#0f141b",
      to: "#404956",
      accent: "#74c7ff",
    },
  },
  {
    id: "honda-accord-touring",
    name: "Accord Touring",
    brand: "Honda",
    model: "Accord",
    year: 2025,
    type: "Sedan",
    location: "Port Harcourt",
    pricePerDay: 50000,
    rating: 4.84,
    trips: 117,
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    range: "910 km",
    featured: false,
    summary: "Refined Honda sedan for executive schedules, smooth commutes, and dependable daily comfort.",
    description:
      "Accord Touring fits clients who want something understated, efficient, and consistently comfortable for business-heavy travel weeks.",
    features: [
      "Hybrid efficiency mode",
      "Heated leather seats",
      "Wireless smartphone integration",
      "Blind spot monitor",
      "Quiet cabin insulation",
    ],
    heroImage: pexels.hondaAccordFront,
    gallery: [
      galleryImage(
        pexels.hondaAccordFront,
        "Front rooftop view",
        "Custom black Honda Accord showcased with high-end details in an urban environment",
      ),
      galleryImage(
        pexels.hondaAccordStreet,
        "Town street view",
        "Black Honda Accord showcased in a lively town setting with people in the background",
      ),
      galleryImage(
        pexels.hondaAccordRear,
        "Rear profile",
        "Rear angle of a black Honda Accord with a sleek fastback silhouette",
      ),
      galleryImage(
        pexels.hondaAccordCloseup,
        "Badge detail",
        "Close-up detail of a black Honda Accord showing the rear emblem and tail light",
      ),
      galleryImage(
        pexels.hondaAccordSide,
        "Side road view",
        "Honda Accord EX-L parked on a gravel road in side profile",
      ),
    ],
    imageAlt: "Custom black Honda Accord showcased with high-end details in an urban environment",
    palette: {
      from: "#10151c",
      to: "#495766",
      accent: "#7ccfff",
    },
  },
  {
    id: "kia-sportage-lx",
    name: "Sportage LX",
    brand: "Kia",
    model: "Sportage",
    year: 2024,
    type: "SUV",
    location: "Benin City",
    pricePerDay: 56000,
    rating: 4.74,
    trips: 93,
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    range: "760 km",
    featured: false,
    summary: "Modern Kia crossover for city errands, small families, and smart hybrid mileage.",
    description:
      "Sportage LX adds a more contemporary everyday SUV option with practical storage, a clean dash layout, and smooth hybrid response.",
    features: [
      "Smart cruise control",
      "Rear occupant alert",
      "Touchscreen navigation",
      "Parking sensors",
      "Split-fold rear bench",
    ],
    heroImage: pexels.kiaSportageFront,
    gallery: [
      galleryImage(
        pexels.kiaSportageFront,
        "Exterior stance",
        "Modern Kia Sportage SUV parked outdoors showing its front fascia",
      ),
      galleryImage(
        pexels.kiaSportageRear,
        "Rear parking angle",
        "Gray Kia Sportage SUV parked on a parking lot showing the rear design",
      ),
      galleryImage(
        pexels.kiaSportageAdventure,
        "Adventure setup",
        "Kia Sportage with mountain bikes on the roof in a scenic forest setting",
      ),
      galleryImage(
        pexels.kiaSportageOffroad,
        "Off-road pair",
        "Kia Sportage SUVs parked off-road in a mountainous landscape",
      ),
    ],
    imageAlt: "Modern Kia Sportage SUV parked outdoors showing its front fascia",
    palette: {
      from: "#0f141a",
      to: "#46515d",
      accent: "#79cbff",
    },
  },
];
